### ISSUE TITLE
Registration and Contact forms with valid info fail with error on form submit

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#274]
In GitLab by @richbodo on Oct 18, 2018, 19:42

These have got to be the same bug or closely related:

**URL**: http://spacebase.co/user/register or http://spacebase.co/contact

**Expected**: Registering as a new user with correct info succeeds and moves through the process of email verification.  Contact form succeeds and sends mail to feedback@spacebase.co

**Observed**: Not much to see in the screenshots

![joinerror](/uploads/7ea4eb6b53494a046121ace738bb4326/joinerror.png)

![contact_error](/uploads/ca49100cf23a159d61de7224ae07de3d/contact_error.png)

### 

Stephen's Notes:
- Very few sites are using nocaptcha_recaptcha. 
- Perhaps was never qa'd? Or did google change something?

Error: Cannot use object of type stdClass as array in Drupal\nocaptcha_recaptcha\NocaptchaValidator->validate()

- The error is occurring when no captcha is entered, and google returns no body. Seems to be an error in the module...
- The problem is not with the returned captcha, which is report success; it's how it's read.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 18, 2018, 19:47

changed title from **Registration a{-s a new user with valid info fails-} with error on form submit** to **Registration a{+nd Contact forms with valid info fail+} with error on form submit**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 18, 2018, 19:47

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 24, 2018, 18:58

Wild estimate, can look more closely and re-estimate if you want

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 24, 2018, 18:58

changed time estimate to 3h

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 25, 2018, 19:14

assigned to @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 00:20

marked this issue as related to #218

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 21:38

mentioned in commit 2eac8583caad824eccb9bd2807b8f8b33ecc51f0

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 21:39

mentioned in merge request !216

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 22:49

mentioned in commit f2c50ed7ae32d18fdde8e7dde94ace9b746ecf95

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 27, 2018, 20:48

Estimate approved.  Thanks, Stephen.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 28, 2018, 02:25

mentioned in merge request !218

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 28, 2018, 03:00

mentioned in commit 5b2c8b9ae35b038ba4d49ba0ba1fb97216b636a3

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 1, 2018, 00:35

assigned to @jayelless

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 1, 2018, 00:41

Hi @StephenCataldo I've tagged our developer @jayelless in this issue as @richbodo mentioned in our project setup call that they wanted immediate progress on some of the bugs. If you know what the issue is a brief summary as a comment here would be great, or if you think it would take longer to explain than to fix then feel free to just commit a fix.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 1, 2018, 02:32

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 1, 2018, 02:33

@richbodo 

I received the the recaptcha keys via lastpass … not working yet, though different errors. Are they recent?

The first thing I’d like to do is log into google’s recaptcha and see if there are explanations for why the previous keys are “invalid domain.” Can I access that?

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 1, 2018, 02:36

@jayelless I created a patch for the recaptcha_nocaptcha module ... which is working on my localhost, not dev, but something has gone wrong giving me “invalid domain” errors (not related, as far as I can tell, to the bug). 

I hope to figure that out (might be as simple as clearing a cache at google, or generating new keys), test, and then submit the bug to Drupal (and at some point use composer to pull in that patch, rather than host it.)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 1, 2018, 03:23

@StephenCataldo @jayelless 

Here is what I know: Stephen shared a link with me and requested I send recaptcha keys. I grabbed those for him.  I can share those via any secure method, but shared them with Stephen via lastpass.  I've never used recaptcha so I just followed Stephens directions, there.

Minus the keys themselves, this is the lastpass entry:

```
From: https://www.google.com/recaptcha/admin#site/343390982?setup

When logged in as a google apps admin for spacebase.co.

Site key
Use this in the HTML code your site serves to users.

Secret key

REDACTED

Use this for communication between your site and Google. Be sure to keep it a secret.

REDACTED

Paste this snippet before the closing </head> tag on your HTML template:
<script src='https://www.google.com/recaptcha/api.js?render=REDACTED'></script>
Paste this snippet in the JavaScript callback for an action on your website.
<script>
grecaptcha.ready(function() {
grecaptcha.execute('REDACTED', {action: 'action_name'})
.then(function(token) {
// Verify the token on the server.
});
});
</script>
The reCAPTCHA documentation site provides details on client side integration for v3.
URL: https://www.google.com/recaptcha/api/siteverify
secret (required)	REDACTED
response (required)	The value of 'g-recaptcha-response'.
remoteip	The end user's ip address.
The reCAPTCHA documentation site describes more details and advanced configurations.
```

Attached screenshot of the top half of the page I created that keypair on.

Happy to provide admin-level google apps logins and anything else you guys need, but will wait for you to ask for that.

![Screen_Shot_2018-11-01_at_12.21.54_AM](/uploads/8de25910f2eed23a479cec928c19113b/Screen_Shot_2018-11-01_at_12.21.54_AM.png)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 1, 2018, 03:39

@jayelless @StephenCataldo - sent you both user account invites to our google apps domain, in case that's helpful.  Awaiting instructions.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 1, 2018, 16:31

Future @ToDo & Notes (non-blocking)

- After this is well qa'd, assuming it works, the patch should be posted to Drupal.
- imo: The nocaptcha module is not necessarily one we want to work with long-run; other better-maintained modules were working on this functionality.
- Creating the keys needs documentation... and keep an eye when we go live. The old keys are working on master and local branches; not dev or qa branches in my short experience. I created a new key using [ stephen@spacebase.co at https://www.google.com/recaptcha/admin#site/343422102?setup ] but I can't see what was going wrong or clear caches for the existing key.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 1, 2018, 18:46

Investigating the original error I find that the following error message is in the Drupal log:
> Exception occurred while trying to send test email from feedback@spacebase.co to james@xequals.co.nz. 400: The parameters passed to the API were invalid. Check your inputs!. 

Using the debugger, I found the following error message being generated:
> Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings. 

Can we please confirm the mailgun API key/working-domain in use in the dev and prod environments?

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 1, 2018, 18:52

I also found what appears to be an error in the Mailgun module.  The file 'src/Plugin/Mail/MailgunMail.php contains the code line:
`      $mailgun_message['h:Reply-To'] = $message['reply-to']; `
but this should probably be:
`      $mailgun_message['reply-to'] = $message['reply-to'];`

This needs to be confirmed when the mailgun api key issue is resolved and if this is a real error then a patch filed against the mailgun module.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 1, 2018, 19:00

@jayelless The error is expected, see https://gitlab.com/spacebase/spacebase/wikis/Development/#viewing-email-logs

Mailgun is configured to only allow certain emails through in the dev & qa & local environments. The error messages when we send from other emails ... are vague.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 1, 2018, 20:37

OK.  The only error I can find on my local environment or the Platform.sh dev environment is that the welcome email is not being sent because the mailgun parameters are invalid. The user account and profile are created correctly as far as I can tell.  I see the message "website has encountered an unexpected error" on the production site, but I have no access to investigate further.  Can someone who does have access please post the contents of the Drupal log for such an event.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 1, 2018, 21:28

Just an observation, as noted by @StephenCataldo  "Very few sites are using nocaptcha_recaptcha" drupal.org has no production release. Xequals would normally use 
https://www.drupal.org/project/honeypot

to solve form submission spam problems, which has a full D8 release, why not just swap the module out? 

Also, have we confirmed that the problem is related to the nocaptcha_recaptcha module by disabling it in a test environment, where it is not needed? We don't have full environment access yet which is slowing us down considerably.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 2, 2018, 00:44

Tom, maybe you can give me a demo of that honeypot thing?  I have never seen it.  Captchas seem pretty normal.  I strongly suspect that the google captcha is fixable, but if it's not, and it's easier to do the honeypot thing, lets do that.

The reason we installed the captcha is typical - Em had to spend hours fighting all the spam data put into the system.  Whatever the solution is, that's the problem.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 2, 2018, 00:57

@richbodo it's hard to demo because it works by presenting elements which only bots will react to, and so is invisible to humans. However, we use it on multiple production sites, and there is a full drupal module release with 131,000 sites using it, so that should tell you plenty. If you want a fast fix I just pop that module in there and disable the captcha module for now.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 2, 2018, 00:59

Just ran a signup test on production and got this error in the logs, which means this is most probably a nocaptcha_recaptcha error, so the quickest course of action is to replace the module with a working one which mostly does the same thing.

Error: Cannot use object of type stdClass as array in Drupal\nocaptcha_recaptcha\NocaptchaValidator->validate() (line 64 of /app/web/modules/contrib/nocaptcha_recaptcha/src/NocaptchaValidator.php) #0 /app/web/modules/contrib/nocaptcha_recaptcha/nocaptcha_recaptcha.module(87): Drupal\nocaptcha_recaptcha\NocaptchaValidator->validate('03AMGVjXil1-yMO...') #1 /app/web/modules/contrib/captcha/captcha.module(430): nocaptcha_recaptcha_validate('test', NULL, Array, Object(Drupal\Core\Form\FormState)) #2 [internal function]: captcha_validate(Array, Object(Drupal\Core\Form\FormState), Array) #3 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(282): call_user_func_array('captcha_validat...', Array) #4 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(238): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState)) #5 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'user_register_f...') #6 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(575): Drupal\Core\Form\FormValidator->validateForm('user_register_f...', Array, Object(Drupal\Core\Form\FormState)) #7 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(318): Drupal\Core\Form\FormBuilder->processForm('user_register_f...', Array, Object(Drupal\Core\Form\FormState)) #8 /app/web/core/lib/Drupal/Core/Controller/FormController.php(93): Drupal\Core\Form\FormBuilder->buildForm('user_register_f...', Object(Drupal\Core\Form\FormState)) #9 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #10 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #11 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #13 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #14 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #16 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /app/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #25 {main}.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 2, 2018, 01:07

Do it to it, Tom.  Replace that sh*t.

And then push to prod, or have me do it.  Today is a good day to die.  Ship!

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 2, 2018, 01:20

Hi Rich, I just don't have access yet, environment setup is taking a long time due to documentation and our unfamiliarity with platform.sh and gitlab. James, as the dev on the project, has a local running so can safely commit, but he's left the office, it being 6:15pm. I'll see if I can rustle him up at home. If you are capable of adding a module, please do so and I'll do the rest.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 2, 2018, 01:34

No worries!  Lets tackle it in the morning.  I've never added a module!

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 2, 2018, 02:01

This is ready for qa on dev (if you don't replace it with another module).

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 2, 2018, 02:05

There are too many people working on this bug with conversations in too many places - the patch has been there a couple days, just trying to get keys that work. Please grab my attention if you need me; I don't think I'm supposed to be logged in.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 2, 2018, 09:32

O.k. thanks for the patch, @StephenCataldo!  Only conversation is in this thread and the only recaptcha keys I know of are the ones I shared with you via lastpass.  This is a good first bug for Tom and Jay to work on.  We'll grab you if we need you! :)

@jayelless @thomasmurphy I'll be sure to share the mailgun login with you and explain that config on slack.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 2, 2018, 09:33

unassigned @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 4, 2018, 20:18

mentioned in merge request !219

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 4, 2018, 20:50

Hi, we're got to know your stack a bit better and have discovered that we need an owner in gitlab to accept merge requests, which is either Rich or Matthew. That's the only thing between us and a production deployment now.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 5, 2018, 23:04

This is now fixed on production.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 5, 2018, 23:04

closed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 28, 2018, 18:09

I'd like to post the patch we're using to Drupal... it would make sense to then change composer to reference the patch there rather than a local copy.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 28, 2018, 18:35

Hi Stephen.  If you have an issue on D.O. then you should post you patch to that issue so it can be referenced in the composer.json file.  What is the module and what is the patch?

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 28, 2018, 19:22

Hi James — 

This issue: https://www.drupal.org/project/nocaptcha_recaptcha/issues/2981948
This patch:            "Validator has json_decode error": "./web/validator_json_decode_error-2981948-1.patch"

It's more of a project mng't question = should I be spending time doing this especially to switch our patch to D.O after it's submitted. @richbodo @thomasmurphy

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Nov 28, 2018, 20:01

Hi, since we're not using this patch currently, due to switching to a honeypot anti-spam approach, it doesn't seem important to me. That said, if it won't take long and you think it will help other people, then it seems like a good use of time. How much time are we talking?

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Nov 28, 2018, 21:11

An hour or two, I expect. Should take nocaptcha and my patch out of composer, I still see them on dev branch, unless you want to do that in a branch already being merged.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 29, 2018, 12:48

@StephenCataldo @jayelless The patch has to go on the back burner for now.  James, take it out of composer.  Stephen, if you want to contribute the patch, I applaud that and support it with two hours of sponsorship.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Dec 5, 2018, 01:56

mentioned in merge request !244

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Dec 10, 2018, 20:31

The contrib module nocaptcha_recaptcha has been removed from the codebase, along with the patch file.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Dec 10, 2018, 20:31

reopened

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Dec 10, 2018, 20:37

mentioned in merge request !245

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:09

Just saw the QA-dev label on this one, ran through both the sign-up and contact forms, with valid info.

Success!

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:09

closed
